name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      db:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRESQL_DATABASE: carriershub_for_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: "24.1.7"
          elixir-version: "1.12.3"

      - name: Install Dependencies
        run: mix deps.get --only test

      - run: mix test

      - run: mix coveralls.github
        if: ${{matrix.coverage}}
